name: ShellCheck

on:
  push:
    branches: [main]
    paths:
      - "**.sh"
  pull_request:
    branches: [main]
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
